// Dispatch constants:

// Fader Channels:
export const SOCKET_SET_FADERLEVEL = 'FaderLevel'
export const SOCKET_SET_INPUT_GAIN = 'InputGain'
export const SOCKET_SET_INPUT_SELECTOR = 'InputSelector'
export const SOCKET_ASSIGN_CH_TO_FADER = 'assignChToFader'
export const SOCKET_REMOVE_ALL_CH_ASSIGNMENTS = 'removeAllChAssignments'
export const SOCKET_SET_FADER_MONITOR = 'FaderMonitor'
export const SOCKET_SHOW_IN_MINI_MONITOR = 'showInMiniMonitor'
export const SOCKET_SET_AUX_LEVEL = 'setAuxLevel'
export const SOCKET_SET_INPUT_OPTION = 'setInputOption'
export const SOCKET_SET_FX = 'setFx'
export const SOCKET_TOGGLE_PGM = 'togglePgm'
export const SOCKET_TOGGLE_VO = 'toggleVo'
export const SOCKET_TOGGLE_SLOW_FADE = 'toggleSlowFade'
export const SOCKET_TOGGLE_PST = 'togglePst'
export const SOCKET_TOGGLE_PFL = 'togglePfl'
export const SOCKET_TOGGLE_MUTE = 'toggleMute'
export const SOCKET_TOGGLE_AMIX = 'toggleAmix'
export const SOCKET_TOGGLE_IGNORE = 'toggleIgnore'
export const SOCKET_NEXT_MIX = 'nextMix'
export const SOCKET_CLEAR_PST = 'clearPst'

// Div:
export const SOCKET_SAVE_SETTINGS = 'saveSettings'
export const SOCKET_RESTART_SERVER = 'restartServer'
export const SOCKET_GET_SNAPSHOT_LIST = 'getSnapshotList'
export const SOCKET_RETURN_SNAPSHOT_LIST = 'returnSnapshotList'
export const SOCKET_GET_CCG_LIST = 'getCcgList'
export const SOCKET_RETURN_CCG_LIST = 'returnCcgList'
export const SOCKET_GET_MIXER_PRESET_LIST = 'getMixerPresetList'
export const SOCKET_RETURN_MIXER_PRESET_LIST = 'returnMixerPresetList'
export const SOCKET_LOAD_MIXER_PRESET = 'loadMixerPreset'
export const SOCKET_LOAD_SNAPSHOT = 'loadSnapshot'
export const SOCKET_SAVE_SNAPSHOT = 'saveSnapshot'
export const SOCKET_SAVE_CCG_FILE = 'saveCcgFile'
export const SOCKET_GET_PAGES_LIST = 'getPagesList'
export const SOCKET_RETURN_PAGES_LIST = 'getPagesList'
export const SOCKET_TOGGLE_ALL_MANUAL = 'toggleAllManual'
export const SOCKET_GET_LABELS = 'getLabels'

// Store updates:
export const SOCKET_SET_FULL_STORE = 'setFullStore'
export const SOCKET_SET_STORE_FADER = 'setStoreFader'
export const SOCKET_SET_STORE_CHANNEL = 'setStoreChannel'
export const SOCKET_SET_MIXER_ONLINE = 'setStoreSettings'
export const SOCKET_SET_PAGES_LIST = 'setPagesList'
export const SOCKET_SET_LABELS = 'setLabels'
export const SOCKET_FLUSH_LABELS = 'flushLabels'
